#### Vectors -
- Next we work on "Vectors" which are One-Dimensional Tensors, or an array of numbers.
- They are arranged in an order so that we can access elements by their index.
- Vectors represent a point in space:
    - length 2 --> point in 2D Space.
    - length 3 --> location in 3D Cube.
    - length n --> location in an nD tensor.


In [70]:
import numpy as np
import torch
import tensorflow as tf

In [71]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [72]:
len(x)

3

In [73]:
x.shape
#the shape is not having columns as we need to declare it in matrix style to do so. Therefore transpose also won't work on this 'x'

(3,)

In [74]:
type(x)

numpy.ndarray

In [75]:
type(x[0])

numpy.int32

#### Vector Tranposition
- Its simply manipulating a vector by flipping itself over its diagonal.
- Reverses the shape of the vector, i.e (1,3) --> (3,1).

In [76]:
x_t =  x.T
x_t
#As discussed, no change seen due to non-matrix declaration

array([25,  2,  5])

In [77]:
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [78]:
y.shape

(1, 3)

In [79]:
y_t = y.T
y_t
#Now tranpose works as expected!

array([[25],
       [ 2],
       [ 5]])

##### Vectors in PyTorch and Tensorflow

In [80]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [81]:
x_pt.shape

torch.Size([3])

In [82]:
x_pt = torch.tensor([[25, 2, 5]])
x_pt

tensor([[25,  2,  5]])

In [83]:
x_pt.shape

torch.Size([1, 3])

In [84]:
a = x_pt.T
a


tensor([[25],
        [ 2],
        [ 5]])

In [85]:
b = torch.transpose(x_pt, 0, 1)
b

tensor([[25],
        [ 2],
        [ 5]])

In [86]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>

In [87]:
x_tf.shape

TensorShape([3])

In [88]:
x_tf = tf.Variable([[25, 2, 5]])
x_tf

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[25,  2,  5]])>

In [89]:
x_tf.shape

TensorShape([1, 3])

In [90]:
c = tf.transpose(x_tf, perm=[1,0])
c

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[25],
       [ 2],
       [ 5]])>