#### Matrix Properties
- We move to the next part of Linear Algebra for ML, where we study properties of Matrices.
- Properties like frobenius norm, matrix multiplication, inversion, diagonal, eigen values etc...

##### Frobenius Norm
- Analogous to L2 Norm in vectors.
- Measures the size of the matrix in terms of Euclidean Distance.
    - Its baiscally the sum of magnitude of all Vectors in the Matrix!

In [139]:
import numpy as np
import torch
import tensorflow as tf

In [140]:
X = np.array([[1,2], [3,4]])
X

array([[1, 2],
       [3, 4]])

In [141]:
(1**2 + 2**2 + 3**2 + 4**2)**(1/2)

5.477225575051661

In [142]:
np.linalg.norm(X)

5.477225575051661

In [143]:
X_pt = torch.tensor([[1,2], [3,4.]])#torch.norm() needs float type
X_pt

tensor([[1., 2.],
        [3., 4.]])

In [144]:
torch.norm(X_pt)

tensor(5.4772)

In [145]:
X_tf = tf.Variable([[1,2], [3,4.]])#tf.norm() also needs float type
X_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [146]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.4772257804870605>

##### Matrix Multiplication
- For 2 matrices, A and B to be multiplied, the number of columns of A must be same as the number of rows of B.
    - i.e. if A --> (mXn) and B --> (nXp) ==> A x B = C where C --> (mXp)
- *IMP* -
    - Matrix multiplication is NOT mandatorily commutative. i.e A x B may not be equal to B x A.

In [147]:
A = np.array([[3,4], [5,6], [7,8]])
B = np.array([[1,9], [2,0]])
b = np.array([1,2]) #Vector, not a matrix
A, B, b

(array([[3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 9],
        [2, 0]]),
 array([1, 2]))

In [148]:
np.dot(A,b)

array([11, 17, 23])

In [149]:
np.dot(A,B)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [150]:
A_pt = torch.tensor([[3,4], [5,6], [7,8]])
B_pt = torch.tensor([[1,9], [2,0]])

A_tf = tf.Variable([[3,4], [5,6], [7,8]])
B_tf = tf.Variable([[1,9], [2,0]])
b_tf = tf.Variable([1,2])

In [151]:
torch.matmul(A_pt, B_pt)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [152]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]])>

In [153]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23])>

##### Symmetric and Identity Matrices
- A symmetric matrix is one where :-
    - Matrix is a square matrix
    - XT = X [transpose is same as matrix]
    - Elements above the diagonal must be mirror images of those below it.

- An Identity matrix is a special case of symmetric matrices, where :-
    - Every element on the main diagonal is 1.
    - Every other element on the matrix is 0.

- It is denoted by In where n = height(or width) of matrix.
- *IMP* - Any matrix or vector multiplied by Identity matrix, results in the matrix or vector itself!

In [154]:
X_sym = torch.tensor([[0,1,2], [1,7,8], [2,8,9]])
X_sym

tensor([[0, 1, 2],
        [1, 7, 8],
        [2, 8, 9]])

In [155]:
X_sym.T

tensor([[0, 1, 2],
        [1, 7, 8],
        [2, 8, 9]])

In [156]:
X_sym.T == X_sym

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [157]:
I = np.identity(3, dtype=int)
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [158]:
I_pt = torch.tensor([[1,0,0], [0,1,0], [0,0,1]])
I_pt

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [159]:
R = torch.tensor([[25,2,5], [2,4,5]])
R

tensor([[25,  2,  5],
        [ 2,  4,  5]])

In [160]:
torch.matmul(R,I_pt)

tensor([[25,  2,  5],
        [ 2,  4,  5]])

##### Matrix Inversion
- The inverse of a matrix M (denoted by M^-1) is a matrix that, when multiplied by M gives the *Identity Matrix*
    - i.e MM^-1 = I
- This is used to solve system of linear equations effeciently.
- *IMP* - The limitation of matrix inversion is that it does NOT work on Singular Matrices.

In [161]:
M = np.array([[4,2], [-5,-3]])
M_pt = torch.tensor([[4,2], [-5,-3.]])
M, M_pt

(array([[ 4,  2],
        [-5, -3]]),
 tensor([[ 4.,  2.],
         [-5., -3.]]))

In [162]:
M_inv = torch.inverse(M_pt)
M_inv

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]])

In [163]:
np.matmul(M_pt, M_inv)

tensor([[1., 0.],
        [0., 1.]])