#### Matrices -
- Two Dimensional array of numbers or Rank 2 Tensors.
- Denoted by uppercase, italics and bold. Elements are uppercase, italics and non-bold(scalars).
- For notation, height is given priority over weight. i.e (nrow, mcol)
- Colon represents a whole row or a column.
    - X:1 --> 1st whole col.
    - X1: --> 1st whole row

In [39]:
import numpy as np
import torch
import tensorflow as tf

In [40]:
X = np.array([[25,2], [5,26], [3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [41]:
X.shape

(3, 2)

In [42]:
X.size

6

In [43]:
X[:,0]

array([25,  5,  3])

In [44]:
X[1,:]

array([ 5, 26])

In [45]:
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

In [46]:
X_pt = torch.tensor([[25,2], [5,26], [3,7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [47]:
X_pt.shape

torch.Size([3, 2])

In [48]:
X_pt[1,:]

tensor([ 5, 26])

In [49]:
X_tf = tf.Variable([[25,2], [5,26], [3,7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [50]:
X_tf.shape

TensorShape([3, 2])

In [51]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [52]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>