##### Basic Tensor Arithmetic
- We can do basic mathematical operations on tensors like - addition, subtraction, multiplication, division etc. 
- For these basic ops, the tensor's each element is simply operated on and changed.
- i.e. if adding 2 to a tensor, its each element will be incremented by 2. Similarly for other ops.
- In PyTorch and Tensorflow, + and * are overloaded when used. At the core - torch.add(), torch.mul(), tf.multiply() and tf.add() are being implemented.

In [75]:
import numpy as np
import torch
import tensorflow as tf

In [76]:
X = np.array([[25,2], [5,26], [3,7]])
X_pt = torch.tensor([[25,2], [5,26], [3,7]])
X_tf = tf.Variable([[25,2], [5,26], [3,7]])

In [77]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [78]:
X*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [79]:
#In PyTorch and Tensorflow, + and * are overloaded when used. At the core - torch.add(), torch.mul(), tf.multiply() and tf.add() are being implemented.
X_pt*2+2

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [80]:
torch.add(torch.mul(X_pt,2 ),2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [81]:
X_tf*2+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [82]:
tf.add(tf.multiply(X_tf,2 ),2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

##### Hadamard Product
- If two tensors of the same size are being operated on with basic arithmetics, they are applied element-wise by default.
- For multiplication, tensors again are simply multiplied element-wise. This is NOT matrix multiplication, but rather called the Hadamard Product.
- The mathematical notation is <math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>A</mi>
  <mo>&#x2299;</mo>
  <mi>X</mi>
</math>

In [83]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [84]:
A = X+2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [85]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [86]:
#HADAMARD
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [87]:
A / X

array([[1.08      , 2.        ],
       [1.4       , 1.07692308],
       [1.66666667, 1.28571429]])

##### Tensor Reduction
- Reduction is a common operation performed on tensors.
- Basically here we calculate the sum of all elements of a tensor.
    - For vector x --> <math xmlns="http://www.w3.org/1998/Math/MathML">
  <munderover>
    <mo data-mjx-texclass="OP">&#x2211;</mo>
    <mrow data-mjx-texclass="ORD">
      <mi>i</mi>
      <mo>=</mo>
      <mn>1</mn>
    </mrow>
    <mrow data-mjx-texclass="ORD">
      <mi>n</mi>
    </mrow>
  </munderover>
  <msub>
    <mi>x</mi>
    <mi>i</mi>
  </msub>
</math>
    - For matrix X --><math xmlns="http://www.w3.org/1998/Math/MathML">
  <munderover>
    <mo data-mjx-texclass="OP">&#x2211;</mo>
    <mrow data-mjx-texclass="ORD">
      <mi>i</mi>
      <mo>=</mo>
      <mn>1</mn>
    </mrow>
    <mrow data-mjx-texclass="ORD">
      <mi>m</mi>
    </mrow>
  </munderover>
  <munderover>
    <mo data-mjx-texclass="OP">&#x2211;</mo>
    <mrow data-mjx-texclass="ORD">
      <mi>j</mi>
      <mo>=</mo>
      <mn>1</mn>
    </mrow>
    <mrow data-mjx-texclass="ORD">
      <mi>n</mi>
    </mrow>
  </munderover>
  <msub>
    <mi>X</mi>
    <mrow data-mjx-texclass="ORD">
      <mi>i</mi>
      <mo>,</mo>
      <mi>j</mi>
    </mrow>
  </msub>
</math>

In [88]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [89]:
X.sum()

68

In [90]:
torch.sum(X_pt)

tensor(68)

In [91]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [92]:
X.sum(axis=0) #sum done on the vertical axis

array([33, 35])

In [93]:
torch.sum(X_pt, 0)

tensor([33, 35])

In [94]:
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31, 10])>

In [95]:
X.sum(axis=1) #sum done on the horizontal axis

array([27, 31, 10])

Many other operations can be applied with reduction along all or a selection of axes, e.g.:

- maximum
- minimum
- mean
- product