#### Matrices -
- Two Dimensional array of numbers or Rank 2 Tensors.
- Denoted by uppercase, italics and bold. Elements are uppercase, italics and non-bold(scalars).
- For notation, height is given priority over weight. i.e (nrow, mcol)
- Colon represents a whole row or a column.
    - X:1 --> 1st whole col.
    - X1: --> 1st whole row

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
X = np.array([[25,2], [5,26], [3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.shape

(3, 2)

In [4]:
X.size

6

In [5]:
X[:,0]

array([25,  5,  3])

In [6]:
X[1,:]

array([ 5, 26])

In [7]:
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

In [8]:
X_pt = torch.tensor([[25,2], [5,26], [3,7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [9]:
X_pt.shape

torch.Size([3, 2])

In [10]:
X_pt[1,:]

tensor([ 5, 26])

In [11]:
X_tf = tf.Variable([[25,2], [5,26], [3,7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [12]:
X_tf.shape

TensorShape([3, 2])

In [13]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [14]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>

#### Generic Tensor Notation -
- Uppercase, bold, italics and Sans Serif --> X
- Number of rank is in subscript for denoting. i.e. Rank 4 will have subscript (i,j,k,l)

We take an example of Rank 4 tensor, common for images.
The 4 dimensions are - Num of Images, Height(px), Width(px), Num of Color Channels

In [15]:
images_pt = torch.zeros([32, 28, 28, 3])
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [16]:
images_tf = tf.zeros([32, 28, 28, 3])
images_tf

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   